version: "3.9"

services:
  mariadb:
    image: mariadb:11
    container_name: smartcart-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: smart_cart_system
      MARIADB_USER: smartcart
      MARIADB_PASSWORD: smartcartpass
    ports:
      - "3307:3306"
    volumes:
      - smartcart_db_data:/var/lib/mysql
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql:ro

  adminer:
    image: adminer:latest
    container_name: smartcart-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mariadb

volumes:
  smartcart_db_data:
